### PR TITLE
Fix bookings

### LINKED ISSUE #75: Update Booking API
# Summary

The booking API needs some enhancements in order to fulfill all needed functionality. 

# Conditions

- [ ] rename `GET: /allBookings` to `GET: /bookings/all` (more REST like)
- [ ] Add `PUT /bookings/{id}` to edit an existing booking (Admin only)
- [ ] Make `PUT /bookings/{id}/cancel` (Admin only)
- [ ] Make `PUT /bookings/{id}/approve` (Admin only)
- [ ] Add additional fields to booking
  - [ ] `discount` (Number) positive or negative number, which will be added to total price (Admin only)
  - [ ] `discountDescription` (String) Description text of the discount (Admin only)
  - [ ] `comment` (String) Comment which can be made on booking (Admin + User)
- [ ] `deposit` (Boolean) should also be editable by the admin. Just like `discount` and `discountDescription`.

Fields which can only be set by admin should just be discarded if set in a request that comes from a user (not admin). Similar functionality has already been implemented for changing the role of a user (`PUT /user/{id}` → `sanitizeUserBodyforRole(...)`

### LINKED ISSUE #87: Fix bookings
I already changed some things of the bookings, so they work together with the frontend and I fixed some bugs. I did the following tasks: 
- Move `discount` and `discountDescription` to booking, as they are different for every booking
- Return `sauna` and `price` directly in the `BookingResponse`, remove dedicated endpoints
- Remove checks if sauna is available, as they did not work (on update) and it's not a requirement
- Change which prices are saved in the `BookingPrice` (not the total price of every item, just the base price)

But there is still some work to be done on the branch `patch/fix-bookings`. Please complete the following tasks: 
- [ ] Calculate the totalPrice like it is calculated in the frontend.
- [ ] Write / Adjust tests for the changed functionality
- [ ] Go over the mails again. Currently all properties are sent, but a lot of them are irrelevant to the user. Maybe we could also just link to the frontend, where the user can have a detailed view of the booking.

### About the total price
This is the code from the frontend:
```ts
let total = receipt.booked.duration * receipt.prices.hourlyRate
total += receipt.booked.transportService * receipt.prices.transportService
total += receipt.booked.saunahImp * receipt.prices.saunahImp
total += receipt.booked.handTowel * receipt.prices.handTowel
total += receipt.booked.wood * receipt.prices.wood
total += receipt.booked.washService ? receipt.prices.washService : 0
total += receipt.booked.deposit ? receipt.prices.deposit : 0
total -=  receipt.booked.discount
return total
```

### PR DESCRIPTION
**Pull request by triumphvalley**
## Summary
- Fixes the bookings, so they can work together with the frontend.

## Related Issues
- Closes #87 
- Fixes #75 

## Definition of Done

- User story
  - [ ] All stated conditions fulfilled
- Code
  - [ ] No more code needed
  - [ ] No known bugs
- Clean Code
  - [ ] JavaDoc has been added
  - [ ] API documentation has been added via annotations (if applicable)
  - [ ] No unavoidable code smells
- Testing
  - [ ] All existing tests pass
  - [ ] New unit tests created according to [CONTRIBUTING.md](./CONTRIBUTING.md#-testing-strategy)
  - [ ] New unit tests pass
- SonarCloud
  - [ ] Quality gate passed
- Compatibility to frontend
  - [ ] Compatibility to staging-frontend verified (running frontend locally in Docker container with image matching the deployed image on staging)

### CODE REVIEW

File: src/main/java/ch/saunah/saunahbackend/dto/BookingPriceResponse.java [hunk 1]
```diff
@@ -14,8 +14,7 @@ public class BookingPriceResponse {
     private double depositPrice;
     private double handTowelPrice;
     private double woodPrice;
-    private double discount;
-    private String discountDescription;
+    private double hourlyRate;
```
Comment (triumphvalley) [inline src/main/java/ch/saunah/saunahbackend/dto/BookingPriceResponse.java:17]: This property is not needed. The hourly rate is the property `price` in the sauna. The hourly rate is defined individually for every sauna in the `price` property.

File: src/main/java/ch/saunah/saunahbackend/service/BookingService.java [hunk 2]
```diff
@@ -163,7 +176,7 @@ public Booking editBooking(int bookingId, BookingBody bookingBody) throws IOExce
         Objects.requireNonNull(bookingBody.getLocation(), "Location must not be null!");
         validateBookingData(bookingBody);
```
Comment (triumphvalley) [inline src/main/java/ch/saunah/saunahbackend/service/BookingService.java:177]: does it now work to update? the last time I tested, it threw errors as it was not available (because of the booking itself)

**Review by cabernin — APPROVED** [review]
WIN_20220221_13_45_46_Pro
Sieht gut aus!

**Review by simonschuhmacher — APPROVED** [review]
Looks good to me
